### ISSUE TITLE
There is a problem with CGDK2

### ISSUE THREAD

**Issue by 1286840533** [pvvx/ATC_MiThermometer#273] opened 2022-11-29 09:43 UTC
After flashing the Custom firmware.  Temperature and humidity both show 0.  E2 is displayed after restoring the original firmware

**Comment by 1286840533** [comment] 2022-11-29 14:33
![Uploading IMG_20221129_211302.jpg…]()
![Uploading IMG_20221129_174336.jpg…]()
![Uploading Screenshot_20221129-213154_Chrome.png…]()

**Comment by bogi-bo** [comment] 2022-12-05 15:44
I have the same Problem Problem, with custom FW 0 and with original E2, or EZ

**Comment by 1286840533** [comment] 2022-12-06 16:55
> I have the same Problem Problem, with custom FW 0 and with original E2, or EZ I have one which I haven't flashed, there is the Firmware v1.1.1_0223.bin as stock

I've tried all the firmware to no avail.

**Comment by pvvx** [comment] 2022-12-12 17:37
Has the sensor type changed?

**Comment by bogi-bo** [comment] 2022-12-12 18:39
> Has the sensor type changed?

What do you mean with this?

**Comment by pvvx** [comment] 2022-12-12 20:35
> What do you mean with this?

It is described that "After flashing Custom firmware. Temperature and humidity show 0."

> Is it possible to download firmware with OTA BLE from a working one and put it to a broken one?

Yes.

**Comment by bogi-bo** [comment] 2022-12-12 21:01
> 
> > Is it possible to download firmware with OTA BLE from a working one and put it to a broken one?
> 
> Yes.
do you have maybe a short instruction or a link? Would be great!
If I can help you with providing Data from the exact sensor inside, just let me know! I'd love to support your great work!

**Comment by pvvx** [comment] 2022-12-13 18:20
https://github.com/pvvx/ATC_MiThermometer/issues/114#issuecomment-979458611

**Comment by bogi-bo** [comment] 2022-12-13 20:32
> [#114 (comment)](https://github.com/pvvx/ATC_MiThermometer/issues/114#issuecomment-979458611)
> 
> > there is the Firmware v1.1.1_0223.bin as stock
> 
> I don't have Firmware v1.1.1_0223

Hope this can help. I've done the instruction and here is the file. 
Thank you again for your support! 

[ff.zip](https://github.com/pvvx/ATC_MiThermometer/files/10221793/ff.zip)

**Comment by pvvx** [comment] 2022-12-13 20:43
Add [Qingping CGDK2 Original Firmware v1.1.1_0223](https://pvvx.github.io/CGPR1/img/Original_OTA_CGDK2_v1.1.1_0223.bin)

**Comment by bogi-bo** [comment] 2022-12-13 20:55
> Сut and added file [Qingping CGDK2 Original Firmware v1.1.1_0223](https://pvvx.github.io/CGPR1/img/Original_OTA_CGDK2_v1.1.1_0223.bin) (The checksum of the original firmware is normal.)
> 
> You can delete your file if you have any concerns about the data from it.

It is working, thank you! 
For me it looks "solved" 

@1286840533 can you try?

**Comment by pvvx** [comment] 2022-12-13 21:02
It remains to find out which sensor is used in the new version.

**Comment by bogi-bo** [comment] 2022-12-13 21:12
> It remains to find out which sensor is used in the new version.

If I can help, let me know…

**Comment by pvvx** [comment] 2022-12-13 21:20
A good [photo of the board](https://pvvx.github.io/CGDK2/) or reading the marking from the sensor is required.
To do this, you need to disassemble the case. The action is complicated by the possibility of spoiling the plastic latches and the rear view of the case...

**Comment by pvvx** [comment] 2022-12-13 22:16
Without sensors, bare TLSR8253, firmware v1.1.1_0223 (fullflash), start log with I2C.
[i2c_log.zip](https://github.com/pvvx/ATC_MiThermometer/files/10222506/i2c_log.zip)
Now guess who is at 0x88 (0x44), and 0xE0(0x70), and 0x00:
![image](https://user-images.githubusercontent.com/12629515/207456162-7bf52238-0e38-4665-8da4-6ebb17c5d2a7.png)
![image](https://user-images.githubusercontent.com/12629515/207456175-6eef300f-25b2-41bf-bde7-62b10f0d7bc1.png)
![image](https://user-images.githubusercontent.com/12629515/207456199-67e24342-ffad-4c00-b390-97b9a580e3c8.png)
![image](https://user-images.githubusercontent.com/12629515/207456204-e3f8a211-3d7d-4db2-b0ba-48be83512a18.png)
![image](https://user-images.githubusercontent.com/12629515/207456214-7bac1f85-ab29-4a1e-84b6-67850464c302.png)

**Comment by pvvx** [comment] 2022-12-14 01:21
I don't see any changes.
And what doesn't work for you?
What does it mean "Problem, with custom FW **0** and with original **E2**, or **EZ**"?

**Comment by bogi-bo** [comment] 2022-12-14 19:07
> I don't see any changes.
> And what doesn't work for you?
> What does it mean "Problem, with custom FW **0** and with original **E2**, or **EZ**"?

I can try to open it and take a picture for you.

a better description would be:
With the custom FW the temperature and humidity is showing 0.0 on both.

when flashing with „original FW 217“ on the display is showing „E2“

according what i‘ve found in a documentation from qingping it says the „sensor“ is broken, so it looks like what you thought, that there is an other sensor.

![3DA8DA30-3A06-4820-A827-0BE46052C18A](https://user-images.githubusercontent.com/45272933/207689972-3afba914-bcf7-41f0-8b8f-57bed0a443da.jpeg)

**Comment by opcode02** [comment] 2022-12-18 17:12
I have the same CGDK2 issue. I took mine apart and took a close up picture of the sensor. It appears its a SHTV3 maybe?

![20221218_110429 (2022-12-18T17_09_22 062)](https://user-images.githubusercontent.com/660708/208310610-43eaabf1-6d30-4b69-85ac-7a380402ad7f.jpg)

**Comment by pvvx** [comment] 2022-12-18 22:28
SHTV3 = SHTC3

**Comment by 1286840533** [comment] 2022-12-22 02:38
> > 删减文件[清平CGDK2 Original Firmware v1.1.1_0223](https://pvvx.github.io/CGPR1/img/Original_OTA_CGDK2_v1.1.1_0223.bin) (原固件校验正常)
> > 如果您对其中的数据有任何疑虑，可以删除您的文件。
> 
> 它正在工作，谢谢！ 对我来说它看起来“解决了”
> 
> @1286840533你能试一下吗？

Sorry for the late reply, this firmware works fine

**Comment by yuchangyuan** [comment] 2022-12-24 04:24
after flash v39, same issue happen(both temp & humi display 0). 

flash https://github.com/pvvx/ATC_MiThermometer/blob/master/Original_OTA_CGDK2_v1.1.1_0223.bin back make device work again.

**Comment by pvvx** [comment] 2022-12-24 06:34
There is no [PCB photo to support the new version of CGDK2](https://github.com/pvvx/ATC_MiThermometer/issues/273#issuecomment-1349720699). Perhaps the circuit related to the sensor has been changed.

**Comment by yuchangyuan** [comment] 2022-12-24 07:47
I use this sensor in bathroom, so I have do hardening, so it may not usefull.

![IMG20221224154005](https://user-images.githubusercontent.com/1221448/209426424-7bfc12b3-6c71-492a-a287-f05892b3e7b5.jpg)
![IMG20221224154041](https://user-images.githubusercontent.com/1221448/209426425-f31d6a12-e29c-4182-9df3-ba156752aaa0.jpg)

**Comment by joe-sydney** [comment] 2022-12-30 06:29
I recently bought a few of these and I am experiencing this issue. Happy to open it up to take a picture of the PCB but it wasn't obvious how to do so. If that would be useful, please let me know how to dismantle it.

**Comment by pvvx** [comment] 2022-12-31 16:50
@yuchangyuan 
The capacitor in the power circuit is excluded. This affects the operation of the device = incomplete use of the battery life!
![image](https://user-images.githubusercontent.com/12629515/210150281-c011f245-113b-45b4-b2df-dd2481307dc6.png)
![image](https://user-images.githubusercontent.com/12629515/210150283-8073bc61-aa1b-46a1-8383-6a2458864331.png)

**Comment by MatMaul** [comment] 2023-01-02 12:56
@pvvx nice catch, any idea if/why it would affect sensor reading ? I am having the same trouble.

I can compile the firmware so let me know if you want me to try out a fix.

**Comment by pvvx** [comment] 2023-01-02 13:04
I don't think it affects the sensor.
Last fortune-telling on the version of CGDK2 that I do not have indicate the possibility of tricky behavior of the i2c bus. :)
Perhaps it is running a modified LCD controller occupying the i2c bus signals.

**Comment by MatMaul** [comment] 2023-01-02 13:49
> And reality says that no one needs it, because. anyone can remove all logs from any bus or just take a photo of a printed circuit board.

I did take the photos yesterday actually. I am not sure the quality is enough however, let me know if you need a clearer view of some parts.
https://photos.app.goo.gl/uaS9eQzTZX1BKiMx7

The sensor itself is definitively a SH3V.

Absolutely please stop buying more :) I have one and can help pretty easily.

I am not sure what you are asking regarding logs, I can easily change code and report. I however don't have any USB-UART around for now, but we can probably dump some values in the EEP to read them afterwards ? Or just dump some values in the ZigBee network frame and read them live ?

I can tinker with the code, but mostly new to this so need some guidance to what/where to look for.

**Comment by MatMaul** [comment] 2023-01-02 13:57
I did take the photos yesterday actually. I am not sure the quality is enough however, let me know if you need a clearer view of some parts.
https://photos.app.goo.gl/ccjWPhPaBh7bHwLh6

The sensor itself is definitively a SH3V.

Absolutely please stop buying more :) I have one and can help pretty easily.

I am not sure what you are asking regarding logs, I can easily change code and report. I however don't have any USB-UART around for now, but we can probably dump some values in the EEP to read them afterwards ? Or just dump some values in the ZigBee network frame and read them live ?

I can tinker with the code, but mostly new to this so need some guidance to what/where to look for.

**Comment by pvvx** [comment] 2023-01-02 14:08
So far the only thing you can find:
Marking = identity:
![image](https://user-images.githubusercontent.com/12629515/210242075-c49efd35-70d1-4f74-97d9-e2877293f966.png)
Differences:
![image](https://user-images.githubusercontent.com/12629515/210242253-1242b208-a7dd-4734-b819-c951dbd1d521.png)
![image](https://user-images.githubusercontent.com/12629515/210242262-58d9fc1f-ba83-48fc-95b5-0000f41c7c6d.png)

**Comment by pvvx** [comment] 2023-01-02 15:34
[CGDK2_test.bin](https://github.com/pvvx/ATC_MiThermometer/blob/master/CGDK2_test.bin) - Firmware for SHTC3 sensor only. No auto-detect.

**Comment by jerome-73** [comment] 2023-01-02 19:17
> [CGDK2_test.bin](https://github.com/pvvx/ATC_MiThermometer/blob/master/CGDK2_test.bin) - Firmware for SHTC3 sensor only. No auto-detect.

Hi,

I've got the same issue and tested the CGDK2_test.bin.
Nothing changed. The display seems to work but displays 0 for temp and humidity.

**Comment by MatMaul** [comment] 2023-01-02 22:21
Same here.

I began adding some "tracing" in `read_sensor_cb` by setting `measured_data.temp`.
First observation, I can see my fake temperature updates in bluetooth, but not on the display, so here is another problem, or a related one.

 It seems like we never receive an ACK: I put 2 different fake temp value in https://github.com/pvvx/ATC_MiThermometer/blob/master/src/sensors.c#L105 and https://github.com/pvvx/ATC_MiThermometer/blob/master/src/sensors.c#L108, and it seems the second is never reached.

Not sure where to go next.

**Comment by pvvx** [comment] 2023-01-04 11:48
This means that the sensor has a different crystal and protocol than what is indicated on the label.
Those. it is necessary to remove the logs from the working sensor from the of.firmware.

**Comment by joe-sydney** [comment] 2023-01-09 09:10
Is there any chance that custom firmware will work on this version of the CGDK2? I just bought several of these and if it's never going to work, perhaps the documentation should be updated with a warning of the risk of being sold the new version.

**Comment by pvvx** [comment] 2023-01-19 09:39
It is possible that a problem with the sensor is detected if the board has protective diodes on the I2C bus. 
A similar situation arose with the new [MJWSD05MMC](https://pvvx.github.io/MJWSD05MMC/), but it was immediately resolved, since the devices are available, unlike the new CGDK2.
The test will be in a new beta version with the number 4.0 later, since no one has helped :)

**Comment by 1286840533** [comment] 2023-01-20 14:44
> It is possible that a problem with the sensor is detected if the board has protective diodes on the I2C bus. A similar situation arose with the new [MJWSD05MMC](https://pvvx.github.io/MJWSD05MMC/), but it was immediately resolved, since the devices are available, unlike the new CGDK2. The test will be in a new beta version with the number 4.0 later, since no one has helped :)

The latest firmware doesn't show the temperature
Status: Hardware Version: CGDK2 2.1.0, Software Version: 4.0
Vbat: 2833 mV , Temp: 0.00°C, Humi: 0.00%, ID: 0, Reed switch counter: 0, flg: 0x01:r1/t0

**Comment by Sawadee2u** [comment] 2023-02-09 00:36
I can confirm that beta 4.1 does not correct the temperature and humidity issue. Still displays "0" for both.
Hardware Version: CGDK2 2.1.0, Software Version: 4.1

**Comment by pvvx** [comment] 2023-02-11 08:48
![image](https://user-images.githubusercontent.com/12629515/218249241-8e0e73a7-1379-4b07-aeae-5b2f17cd3093.png)

Requires documentation or log taken from a working SHTV3 AAC29.

**Comment by Sawadee2u** [comment] 2023-02-11 13:35
I have the skills to do this but not the knowledge of this device interface.
What device do I need to interface with this device?
Can you point me to documentation?
Also. If you would like me to send you one (unopened) I will be happy to. Whatever I can do to help.

**Comment by Giom-fm** [comment] 2023-02-16 18:36
> after flash v39, same issue happen(both temp & humi display 0).
> 
> flash https://github.com/pvvx/ATC_MiThermometer/blob/master/Original_OTA_CGDK2_v1.1.1_0223.bin back make device work again.

@yuchangyuan How did you manage to flash the device back. After the "E2" error im not able to connect to the device again.

```
19:08:36: Searching for devices
19:08:38: Connecting to: Qingping Temp RH Lite
19:08:42: Not found Telink OTA service!
19:08:42: Disconnected.
```

**Comment by Sawadee2u** [comment] 2023-02-16 19:42
I got the E2 notice also. I was able to reflash with the 223 bin after pulling the battery and replacing.

**Comment by Giom-fm** [comment] 2023-02-16 20:02
Unfortunately, I have had no success so far.

**Comment by Sawadee2u** [comment] 2023-02-16 20:29
Sorry to hear that. For what it’s worth, I was able to reprogram with 4.0 then 4.1 then back to233 bin. I only did one unit so may have been dumb luck.. I also held down the reset button for 10 seconds or do. This is the button that changes C to F. I believe the display flashed. Best of luck. Hoping for an update.I do have this working with Home Assistant using 233 bin and bind key.* * * * * * * * * * * * * * * * * * * * * * *“Beer is Proof that God Loves Us and Wants Us to Be Happy"  Benjamin Franklin* * * * * * * * * * * * * * * * * * * * * * *On Feb 16, 2023, at 3:02 PM, Guillaume Fournier ***@***.***> wrote:﻿
Unfortunately, I have had no success so far.

**Comment by mafrmt00** [comment] 2023-02-17 08:22
The Sensor used is a SHTV3
![PXL_20230216_153838257](https://user-images.githubusercontent.com/11454230/219590321-4d2a20bb-d1e2-48fe-8ba2-723a0dece48a.jpg)
The Datasheet is:
[HT_DS_SHTC3_D1.pdf](https://github.com/pvvx/ATC_MiThermometer/files/10764705/HT_DS_SHTC3_D1.pdf)

I took a quick look into I2c with the stock firmware.
![PXL_20230217_081431730](https://user-images.githubusercontent.com/11454230/219591052-259cb237-4555-401d-b8d0-7c7ac338d1f7.jpg)
![PXL_20230217_081541865](https://user-images.githubusercontent.com/11454230/219591100-f77d09e4-9b83-4b6a-9682-a40d658c5d98.jpg)

As you can see, the address is 0x70 and the sleep/wakeup commands are according to the datasheet.

I hope this helps.

**Comment by yuchangyuan** [comment] 2023-02-21 02:21
> 


> > after flash v39, same issue happen(both temp & humi display 0).
> > flash https://github.com/pvvx/ATC_MiThermometer/blob/master/Original_OTA_CGDK2_v1.1.1_0223.bin back make device work again.
> 
> @yuchangyuan How did you manage to flash the device back. After the "E2" error im not able to connect to the device again.

I can still connect to the sensor, maybe I replace battery as @Sawadee2u do, I forget the details. Replace with a new battery maybe necessary because flashing will consume a lot of power.

> ```
> 19:08:36: Searching for devices
> 19:08:38: Connecting to: Qingping Temp RH Lite
> 19:08:42: Not found Telink OTA service!
> 19:08:42: Disconnected.
> ```

**Comment by mafrmt00** [comment] 2023-02-21 07:57
> > 
> 
> > > after flash v39, same issue happen(both temp & humi display 0).
> > > flash https://github.com/pvvx/ATC_MiThermometer/blob/master/Original_OTA_CGDK2_v1.1.1_0223.bin back make device work again.
> > 
> > 
> > @yuchangyuan How did you manage to flash the device back. After the "E2" error im not able to connect to the device again.
> 
> I can still connect to the sensor, maybe I replace battery as @Sawadee2u do, I forget the details. Replace with a new battery maybe necessary because flashing will consume a lot of power.
> 
> > ```
> > 19:08:36: Searching for devices
> > 19:08:38: Connecting to: Qingping Temp RH Lite
> > 19:08:42: Not found Telink OTA service!
> > 19:08:42: Disconnected.
> > ```

In my case, withe SW displaying E2 I only was able flash it via USB.

**Comment by pvvx** [comment] 2023-02-21 13:49
> As you can see, the address is 0x70 and the sleep/wakeup commands are according to the datasheet.

This is the protocol used in custom fw for CGDK2.
All versions for all types of thermometers use the same driver. The driver supports 2 types: SHTV3(SHTC3) and SHT4x.

**Comment by mafrmt00** [comment] 2023-02-21 14:47
> @mafrmt00 - What version of CGDK2 do you have?

The Version with the problem. It shows only zeros when flashed with alternative firmware and E2 with the older stock firmware. (also with the missing capacitor as described in this thread)

**Comment by pvvx** [comment] 2023-02-21 14:52
Logs of commands to measure and read data from the sensor are required.
The rest matches so far.

**Comment by mafrmt00** [comment] 2023-02-21 14:53
Ok, maybe this helps:
![PXL_20230217_082658125](https://user-images.githubusercontent.com/11454230/220378606-e03771f7-4598-4cde-ad29-ffc652a6a7c8.jpg)

**Comment by pvvx** [comment] 2023-02-21 14:58
What it is: _Transfer at Address = 0x00?_

**Comment by mafrmt00** [comment] 2023-02-21 15:01
![PXL_20230217_082459024](https://user-images.githubusercontent.com/11454230/220380838-bcdc0956-93bf-4ed5-b96a-f3560fe015e9.jpg)
I have no idea, but it happens quite often:

**Comment by pvvx** [comment] 2023-02-21 15:07
That is, some kind of crooked sensor that does not work according to the description in the documentation.

**Comment by mafrmt00** [comment] 2023-02-21 15:28
I think we are getting somewhere.
General call is mentioned in the datasheet. But only for reset (0x0006). 
But the data shown in my picture (0x7ca2) is a valid command (Read T first)

So maybe instead of it's real address the sensor somehow only works with the general call address.

**Comment by pvvx** [comment] 2023-02-21 16:22
When creating a "General Calling Address", the next byte must indicate the address of the device.
But according to the oscillogram, everything is not so.

**Comment by mafrmt00** [comment] 2023-02-21 16:33
Sure, it violates every spec. It seems, just replace 0x70 with 0x00 for read commands.

**Comment by pvvx** [comment] 2023-02-21 18:07
How do I know which commands didn't have responses for sensors I don't have?

**Comment by pvvx** [comment] 2023-02-21 19:46
Test of operation on defective SHTv3 sensors.
CGDK2_v42.bin replaced.

**Comment by mafrmt00** [comment] 2023-02-21 19:57
It still displays only zeros.

_20:49:59: Received device infos are correct
20:49:59: Login successfull
20:50:06: File: CGDK2_v42_test.bin
20:50:06: File size: 78372 bytes
20:50:06: Count: 4899
20:50:08: Start DFU
20:50:29: Update done after 20.555 seconds
20:50:30: Disconnected.
20:51:17: Searching for devices
20:51:38: Connecting to: Qingping Temp RH Lite
20:51:50: Hardware Revision String: 2.1.0
20:51:50: Detected custom Firmware
20:51:50: Hardware Version: CGDK2 2.1.0, Software Version: 4.2, Sensor: SHTC3 (SHTV3)
20:51:50: Custom config HEX string: 55012000002804a9313186b4000000
20:52:07: File: Original_OTA_CGDK2_v1.1.1_0223.bin
20:52:07: File size: 116100 bytes
20:52:07: Count: 7257
20:52:11: Start DFU
20:53:10: Update done after 58.157 seconds
20:53:14: Disconnected._

**Comment by mafrmt00** [comment] 2023-02-21 19:58
On Thursday, I think I will have time to search for a I2C logger and record the whole communication.

**Comment by pvvx** [comment] 2023-02-21 20:09
It's useless.
If it does not work for you, then this means that the "measure" command was executed by the sensor at address 0x70 and confirmed by ACK.
Reading data after the "measure" instruction has been executed requires a NACK check.

**Comment by pvvx** [comment] 2023-02-22 08:27
20:50:06: File: CGDK2_v42_test.bin
This is not the file. Then there was an auto-include in TelinkMiFlasher.html (v4.2 beta).
Now [CGDK2n_v42.bin](https://github.com/pvvx/ATC_MiThermometer/blob/master/CGDK2n_v42.bin) is temporarily available with commands at 0x00 without any auto-recognition, and "Beta v4.2" has been restored.

**Comment by joe-sydney** [comment] 2023-02-22 09:13
And I spoke too soon! Changed to the Mihome type and it is now integrated into HA.

**Comment by mafrmt00** [comment] 2023-02-22 10:43
> > 20:50:06: File: CGDK2_v42_test.bin
> 
> This is not the file. Then there was an auto-include in TelinkMiFlasher.html (v4.2 beta). Now [CGDK2n_v42.bin](https://github.com/pvvx/ATC_MiThermometer/blob/master/CGDK2n_v42.bin) is temporarily available with commands at 0x00 without any auto-recognition, and "Beta v4.2" has been restored.

Works like a charm!

**Comment by pvvx** [comment] 2023-02-22 15:22
This [patch](https://github.com/pvvx/ATC_MiThermometer/blob/master/src/sensors.c#L14) is for testing purposes only and is not suitable for regular CDG firmware. On a normal sensor, such firmware does not work...

**Comment by mafrmt00** [comment] 2023-02-22 15:37
> This [patch](https://github.com/pvvx/ATC_MiThermometer/blob/master/src/sensors.c#L14) is for testing purposes only and is not suitable for regular CGDK2 firmware. On a normal sensor, such firmware does not work... It is required to somehow identify the wrong sensors.

I2C Scan for 0x70. Then reading the values in the regular way. If they are Zero (Wich should never happen with a real measurement), reading the values with 0x00 address.

**Comment by 1286840533** [comment] 2023-02-22 15:55
> 此[补丁](https://github.com/pvvx/ATC_MiThermometer/blob/master/src/sensors.c#L14)仅用于测试目的，不适用于常规 CGDK2 固件。在普通传感器上，这样的固件不起作用...... 需要以某种方式识别错误的传感器。

The temperature and humidity are still a constant, but at least not zero.
Status: Hardware Version: CGDK2 2.1.0, Software Version: 4.2
Vbat: 2717 mV , Temp: 60.07°C, Humi: 36.25%, ID: 2, Reed switch counter: 3, flg: 0x05:r1/t0

**Comment by Giom-fm** [comment] 2023-03-05 13:45
> > > 
> > 
> > 
> > > > after flash v39, same issue happen(both temp & humi display 0).
> > > > flash https://github.com/pvvx/ATC_MiThermometer/blob/master/Original_OTA_CGDK2_v1.1.1_0223.bin back make device work again.
> > > 
> > > 
> > > @yuchangyuan How did you manage to flash the device back. After the "E2" error im not able to connect to the device again.
> > 
> > 
> > I can still connect to the sensor, maybe I replace battery as @Sawadee2u do, I forget the details. Replace with a new battery maybe necessary because flashing will consume a lot of power.
> > > ```
> > > 19:08:36: Searching for devices
> > > 19:08:38: Connecting to: Qingping Temp RH Lite
> > > 19:08:42: Not found Telink OTA service!
> > > 19:08:42: Disconnected.
> > > ```
> 
> In my case, with the SW displaying "E2" I only was able flash it via USB.

Ok I will try it.
How did you manage to open the device without destroying the enclosure?

**Comment by mafrmt00** [comment] 2023-03-05 19:44
> > > > 
> > > 
> > > 
> > > > > after flash v39, same issue happen(both temp & humi display 0).
> > > > > flash https://github.com/pvvx/ATC_MiThermometer/blob/master/Original_OTA_CGDK2_v1.1.1_0223.bin back make device work again.
> > > > 
> > > > 
> > > > @yuchangyuan How did you manage to flash the device back. After the "E2" error im not able to connect to the device again.
> > > 
> > > 
> > > I can still connect to the sensor, maybe I replace battery as @Sawadee2u do, I forget the details. Replace with a new battery maybe necessary because flashing will consume a lot of power.
> > > > ```
> > > > 19:08:36: Searching for devices
> > > > 19:08:38: Connecting to: Qingping Temp RH Lite
> > > > 19:08:42: Not found Telink OTA service!
> > > > 19:08:42: Disconnected.
> > > > ```
> > 
> > 
> > In my case, with the SW displaying "E2" I only was able flash it via USB.
> 
> Ok I will try it. How did you manage to open the device without destroying the enclosure?

Use a small screwdriver to get the inner cover (the part with the hole for the battery) out. It is not glued in and requires very little force.

**Comment by Sawadee2u** [comment] 2023-03-18 19:13
I am unable to get a second of the four CGDK2-wacko devices to program without the resulting zeros for Temp and Humid after getting one (F525) to work.

MAC for these four devices received at the same time
F51A zeros with v41 and v42 and CGDK2n_v42.bin
F525 This was the first one I tried to program and got zeros with v41 and v42 but it took CGDK2n_v42.bin dated 2/22
F536 zeros with v41 and v42 and CGDK2n_v42.bin
F558 zeros with v41 and v42 and CGDK2n_v42.bin

I can get the three, that will not work with CGDK2n_v42.bin, to take the factory FW 1.1.1_0223 and work with Home Assistant through the Xiaomi BLE app. These show Temp, Humid, Battery Voltage, Battery %, and Signal in dbm.
F525 shows up in BT Home app and shows Temp, Humid, Battery Voltage, Battery %, Signal in dbm, Packet id, and Power.
F525 updates data every 10 seconds which is programmable but the other three with factory FW update about every 10 mins.

I just don't know why I can't get these other three to work with any version of the custom FW. Must be doing something different but can't understand what.

**Comment by cultur98** [comment] 2023-03-23 17:13
And the next one with the 0° 0% Problem.
Three devices only work after flashing back to FW 1.1.1_023.
HW Version is 2.1.0
@pvvx Do you want me to send one to you for further analysis?

**Comment by pvvx** [comment] 2023-03-24 02:27
I do not accept any donations except information.

**Comment by cultur98** [comment] 2023-03-24 11:58
Thanks for the quick response.
Unfortunately command  0x03 does not provide any output on the GD2
```
12:04:47: Searching for devices
12:04:52: Connecting to: CGD_14FF31
12:05:16: Hardware Revision String: 2.1.0
12:05:16: Software Revision String: V4.2
12:05:16: Detected custom Firmware
12:05:16: Hardware Version: CGDK2 2.1.0, Software Version: 4.2, Sensor: SHTC3 (SHTV3)
12:05:16: Custom config HEX string: 55011000002804a9313186b4
12:05:26: Settings 0370 was send successful
12:05:48: Settings 4 was send successful
12:05:49: I2C Read/Write fault! (255)
12:05:59: Settings 3 was send successful
12:06:43: Settings 2 was send successful
12:06:44: Sensor: I2C addres 0x70, LCD driver: I2C addres 0x3E
```
I also tried the 0x03 command on some LYWSD03MMCs and a MHO-C401 .
But no output to be seen on the console.
Does it require a parameter?

**Comment by cultur98** [comment] 2023-03-24 18:30
Well aye!
JavaScript debugging console.
Sorry, now the bell rings.

Anyhow I can provide this from the console:
0x1f1f 
ten out of sixteen bits are set ..
```
Send cmd (3303): Query 3 measurements
TelinkMiFlasher.html:1630 Send cmd ok
TelinkMiFlasher.html:1630 Custom (0x1f1f) Notifications id: 0x33 [00]
TelinkMiFlasher.html:1630 Vbat: 2772 mV , Temp: 0.00°C, Humi: 0.00%, ID: 0, Reed switch counter: 0, flg: 0x00:r0/t0
TelinkMiFlasher.html:1630 Vbat: 2773 mV , Temp: 0.00°C, Humi: 0.00%, ID: 0, Reed switch counter: 0, flg: 0x00:r0/t0`
```

**Comment by cultur98** [comment] 2023-03-24 18:34
Ok, the [00] is the response.

One of my LYWSD03MMCs  provided 0x78e0 as an answer?

```
Send: 3
TelinkMiFlasher.html:1630 Custom (0x1f1f) Notifications id: 0x03 [78e0]
TelinkMiFlasher.html:1630 Vbat: 2406 mV , Temp: 19.66°C, Humi: 51.40%, ID: 5536, Reed switch counter: 0, flg: 0x0E:r0/t1
```
But why does the scanner return 0x00 while the display of the CGD2 shows 0° and 0% hum?
At least the display addressed well.
Stranissio!

**Comment by pvvx** [comment] 2023-03-25 06:31
LYWSD03MMC B1.4
02 -> Sensor: I2C addres 0x70, LCD driver: I2C addres 0x3C
03 -> Custom (0x1f1f) Notifications id: 0x03 [78e0]

LYWSD03MMC B1.9
02 -> Sensor: I2C addres 0x44, LCD driver: I2C addres 0x3E
03 -> Custom (0x1f1f) Notifications id: 0x03 [7c88]

CGG1-M 2022
02 ->  Sensor: I2C addres 0x70, LCD driver: I2C addres 0x00
03 -> Custom (0x1f1f) Notifications id: 0x03 [e0]

MJWSD05MMC V2.3
02 -> Sensor: I2C addres 0x44, LCD driver: I2C addres 0x3E, RTC: I2C addres 0x51
03 -> Custom (0x1f1f) Notifications id: 0x03 [7c88a2]

CGDK2 2.1.0
02 -> Sensor: I2C addres 0x70, LCD driver: I2C addres 0x3E
03 -> Custom (0x1f1f) Notifications id: 0x03 [7ce0]

...

**Comment by cultur98** [comment] 2023-03-25 09:07
After reading the entire entry I flashed  CGDK2n_v42.bin with the  [patch ](https://github.com/pvvx/ATC_MiThermometer/blob/master/src/sensors.c#L14) and now it the device shows correct values.
Somehow this patched version is not in the current repository anymore. So I recompiled it.

**Comment by cultur98** [comment] 2023-03-25 11:23
> The worst of all supported thermometer options in terms of battery consumption is CGDK2. Consumption of a working LCD controller and screen - from 9 µA. Plus, in all the latest released versions of CGDK2, power capacitors are not soldered. In the old versions, they were soldered. This reduces the battery life by another 40%. And leads to instability of the main SoC. The LCD controller is buggy at subzero temperatures. Now some CGDK2 sensors are defective... At the same time, the price of CGDK2 is overstated and is equal to thermometers on E-Ink. It's time to remove them from support.

Do you know the value of the capacitor?
Just for those who are crazy enough to retrofit them.

**Comment by pvvx** [comment] 2023-03-25 11:25
And what are the problems with showing the days of the week?

**Comment by pvvx** [comment] 2023-03-25 11:50
> Do you know the value of the capacitor? Just for those who are crazy enough to retrofit them.

https://pvvx.github.io/CGDK2/
![image](https://user-images.githubusercontent.com/12629515/227715780-ac271b09-6fd2-48fb-be2d-d35997f9e6e2.png)

**Comment by cultur98** [comment] 2023-03-26 09:46
> I don't see the point in buying and modifying bad things.
Valued Victor. I totally understand your point here.
If I would have known how crappy the CGDK2s are I would NEVER HAVE bought them.
But since I am having three of them on my table I just want to make the best out of it,
instead of chucking them.
If the MHO-C401s would have been available, they surely would have been my choice.
Hätte hätte ...

**Comment by pvvx** [comment] 2023-03-27 00:57
Capacitors are different. Some have a large leakage current comparable to the consumption of a thermometer. 
The general recommendation is an SSD with a capacity from 22 to 47 UF and a voltage of 25 V. The higher the voltage rating, the lower the leakage current.

**Comment by pvvx** [comment] 2023-03-27 06:06
v4.3: Added "Sensor ID".
Command `05`
SHTC3  "Sensor ID: 00000887"
https://sensirion.com/products/catalog/SHTC3/
![image](https://user-images.githubusercontent.com/12629515/227854350-b1a82737-4964-42d6-9f68-9f30fd7db14a.png)

SHT4x - id 2x16 bits...

**Comment by cultur98** [comment] 2023-03-27 07:18
> @cultur98 - If the new CGDK2 will have a different 'Sensor ID', then auto-detection is possible.

```
09:14:08: Hardware Version: CGDK2 2.1.0, Software Version: 4.3, Sensor: SHTC3 (SHTV3)
09:14:08: Custom config HEX string: 55251000002804a9313186b4
09:14:13: Settings 5 was send successful
09:14:15: Sensor ID: 00000000
```
It is "zero".

**Comment by cultur98** [comment] 2023-03-27 11:20
> So there is also no response to the "Read ID" command. Therefore, this command will not be able to identify the curved sensor.
> 

This is sad but still a little strange since temperature and humidity are read correctly when applying the 
 `#define BAD_SENSOR 1` patch to firmware 4.3.

```
Status: Hardware Version: CGDK2 2.1.0, Software Version: 4.3
Vbat: 2841 mV , Temp: 18.26°C, Humi: 52.66%, ID: 2884, Reed switch counter: 0, flg: 0x0E:r0/t1
```
 

 Well it is probably really not worth spending that much effort.

**Comment by cultur98** [comment] 2023-03-27 19:18
Since I try to avoid MS Windows  I did a build script for Linux which I called MakeAll.sh

```
#!/bin/bash

SWVER=_v43

make_bin () {
  BIN_FILE=$1$SWVER".bin"
  echo "============================"
  echo "  Building $BIN_FILE"
  echo "============================"
  DEV_STRING=$2
  rm -f BIN_FILE
  make -s -j PROJECT_NAME=$1$SWVER POJECT_DEF="$DEV_STRING"
}

make_bin "ATC" "-DDEVICE_TYPE=DEVICE_LYWSD03MMC"
make_bin "BTH" "-DDEVICE_TYPE=DEVICE_MJWSD05MMC"
make_bin "CGDK2" "-DDEVICE_TYPE=DEVICE_CGDK2"
make_bin "CGG1" "-DDEVICE_TYPE=DEVICE_CGG1 -DDEVICE_CGG1_ver=0"
make_bin "CGG1M" "-DDEVICE_TYPE=DEVICE_CGG1 -DDEVICE_CGG1_ver=2022"
make_bin "MHO_C401" "-DDEVICE_TYPE=DEVICE_MHO_C401"
make_bin "MHO_C401N" "-DDEVICE_TYPE=DEVICE_MHO_C401N"
```

**Comment by pvvx** [comment] 2023-03-28 11:11
> This is sad but still a little strange since temperature and humidity are read correctly when applying the 
> #define BAD_SENSOR 1 patch to firmware 4.3.

This fix has not been tested. 
The sensor may not enter sleep mode and the total consumption will increase greatly.
For a complete analysis of the situation, it is required to measure the consumption current on a Power Profiler or similar.
The current consumption between the BLE-advertising transmissions with the display turned off should be less than 2 µA.
The option to turn off the display was introduced in new versions, but not finalized everywhere, since the commands of all controllers are unknown. It is advisable to restart the power supply after selecting - pull out and insert the battery for more than 5 minutes, because if there is a capacitor in the power supply, then its discharge is very long.

**Comment by cultur98** [comment] 2023-03-28 16:59
Ok, I got hold of some measurement gear here.
I hope I was using it the correct way ..

First of all: my CGDK2 also has no power capacitor.
I made measurements with a switched power supply.
That's why you can see periodic changes.
I might repeat the measurement with a more stable power supply on the weekend.

On y-axis 1div is always 1V which equals to 1µA of current.
The yellow marker on the left is on 0V (0µA).

CGDK2_v43.bin - LCD on
![CGDK2_v43 LCD_on](https://user-images.githubusercontent.com/68771519/228310123-44656af1-ad15-4459-b521-cc39f7d44a76.png)
Peak current: 3.4µA - periodic double drops every ~ 82ms 

CGDK2_v43.bin - LCD off
![CGDK2_v43 LCD_off](https://user-images.githubusercontent.com/68771519/228312334-cf9d106b-17b8-4284-a79f-dfd216df4ee1.png)
not to much of a difference compared to LCD on

Original_OTA_CGDK2_v1.1.1_0223.bin
![Cust_v1 1 1_0223](https://user-images.githubusercontent.com/68771519/228312371-8a577cfb-93b4-4d78-954e-babf593a2671.png)
Peak current also in the 3.4µA range - periodic drops only every 1200ms 
=> more average current consumption compared to the custom firmware.

**Closed** 2023-05-07 23:44 UTC
